version: '3'
services:
  jenkins:
    container_name: jenkins-new
    image: jenkins-new
    build:
      context: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
    volumes:
      - C:/Development/projects/jenkins/new_jenkins/jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
networks:
  net: